### PR TITLE
fix: dump a valid yml object with all the types

### PR DESCRIPTION
**Pull request by fboucquez**
--output is currently not exporting valid YAML files/objects.

This PR fixes it. 

Examples:
````
python3 -m catparser --schema ../catbuffer-schemas/symbol/all.cats --include ../catbuffer-schemas/symbol --output symbol.yml
python3 -m catparser --schema ../catbuffer-schemas/nem/all.cats --include ../catbuffer-schemas/nem --output nem.yml
python3 -m catparser --schema ../catbuffer-schemas/symbol/transfer/transfer.cats --include ../catbuffer-schemas/symbol --output transfer.yml
````

[exported_files.zip](https://github.com/symbol/catbuffer-parser/files/7145834/exported_files.zip)

### CODE REVIEW

**Review by rg911 — COMMENTED** [review]
I think you can dump all types using the --schema arg (`all.cats`)?

**Comment by rg911** [comment]
> I think you can dump all types using the --schema arg (`all.cats`)?

ah, sorry I misunder

**Comment by gimre-xymcity** [comment]
You're correct that the output is not valid, however the change has two side-effects:
  1. it changes the order (I don't have strong opinion, but I think order in yaml output should match order in schema files)
  2. whole file is one big obj and it probably should be a list...

**Comment by gimre-xymcity** [comment]
alternative take: https://github.com/symbol/catbuffer-parser/commit/3450d6aa19e574b7b3fb6dc84c1894d582606e4e

[after.zip](https://github.com/symbol/catbuffer-parser/files/7169436/after.zip)

**Comment by fboucquez** [comment]
> You're correct that the output is not valid, however the change has two side-effects:
> 
> 1. it changes the order (I don't have strong opinion, but I think order in yaml output should match order in schema files)
> 2. whole file is one big obj and it probably should be a list...

Big object or large list is fine. This commit drops the object as-is from the parser.
The big object/dictionary structure worked out of the box when I moved the _main_  to https://github.com/symbol/catbuffer-generators/pull/165. 

Parser -> big object yml -> generator  
vs
Parser -> big dic -> large list yml -> big dic -> generator

Having said that,  https://github.com/symbol/catbuffer-parser/commit/3450d6aa19e574b7b3fb6dc84c1894d582606e4e should probably dump one big list instead of simulating the yml output with the the for-each output dumps (with tabbing, dashes and new lines). This caused the issue in the first place.

**Comment by gimre-xymcity** [comment]
`should probably dump one big list instead` - hmm, yeah, fair point...

**Comment by gimre-xymcity** [comment]
done, but output is bit uglier (as name might not be first elem)

https://github.com/symbol/catbuffer-parser/commit/4aac596817af1c1921497dea8594f3312dd1a9d4

[after.zip](https://github.com/symbol/catbuffer-parser/files/7169981/after.zip)

**Comment by fboucquez** [comment]
> i

That's cool, the generator can index by name once the list is loaded. 

Is it possible to re-publish to pypi?
The latest catparser is a bit old https://pypi.org/project/catparser/

**Comment by gimre-xymcity** [comment]
> The latest catparser is a bit old

@fboucquez just to make sure we're on the same page: you mean 2.0.1?

**Comment by fboucquez** [comment]
> > The latest catparser is a bit old
> 
> @fboucquez just to make sure we're on the same page: you mean 2.0.1?

The catparser 2.0.1 in pyp still expects --generator (that has been removed in dev). And of course, it doesn't include this or another yml dump fix.  Is there any dev/alpha pip from the dev branch? Keen to install the tool

**Comment by fboucquez** [comment]
Please ignore, I have just found that you are doing prereleases, like https://pypi.org/project/catparser/2.0.1a230/
Thanks!

**Comment by gimre-xymcity** [comment]
anyway, 2.0.2 is in progress, closing this issue

**Pull request closed without merging**
